module: src.client.agents.HTTPAgent
parameters:
  url: https://api.openai.com/v1/chat/completions
  headers:
    Content-Type: application/json
    Authorization: 
      - Bearer <% PUT-YOUR-OPENAI-KEY-HERE %>
      - Bearer <% PUT-YOUR-OPENAI-KEY-HERE %>
      - Bearer <% PUT-YOUR-OPENAI-KEY-HERE %>
      # You can place any number of keys here, and they will be invoked equally.
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
