module: "src.tasks.LateralThinkingPuzzle_zh"
parameters:
    name: "LateralThinkingPuzzle-dev"
    round: 25
    filepath: "data/lateralthinkingpuzzle_zh/dev.xlsx"
    eval_yaml: "configs/agents/local/turbo.yaml"
