module: "src.agents.api_agents.OpenAICompletion"
parameters:
    name: "text-davinci-002"
    api_args:
        model: "text-davinci-002"
        # key: <assign your openai key here>
        # base: <assign your openai base here>
        timeout: 120
        max_tokens: 256
