default:
  module: src.server.tasks.dbbench.DBBench
  parameters:
    concurrency: 1
    max_round: 15

dbbench-dev:
  parameters:
    name: dbbench-dev
    data_file: "data/dbbench/dev.jsonl"

dbbench-std:
  parameters:
    name: dbbench-std
    data_file: "data/dbbench/standard.jsonl"
